### ISSUE TITLE
Drag and Drop permission

### ISSUE THREAD

**Issue by Firesphere** [hamishcampbell/silverstripe-securefiles#5]
Users can still easily drag and drop files from their own folder into other users folders. This is a security issue that's quite serious.

Haven't found a solution yet (haven't looked at it either btw, came up just an hour or so ago).

Also, the popup warning "denied" is empty (at least, when interface language is set to Dutch)

**Comment by hamishcampbell** [comment]
Unfortunately the CMS `AssetAdmin` doesn't always provide the hooks I'd need to fix this without creating an entire AssetAdmin subclass. For example in the `movemarked` method at:

https://github.com/silverstripe/silverstripe-cms/blob/2.4/code/AssetAdmin.php#L378

As you can see, AssetAdmin doesn't appear to respect File or Folder `canEdit` hooks - perhaps because File/Folder objects don't have an effectual `canEdit` without SecureFiles.

The best solution seems to be create a new AssetAdmin that does it right - but overriding the relevant methods and adding the hooks that are missing.
